name: 'Create a new test app'

run-name: "Create a new test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true
        default: '<YourAppName>.Test'
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range
        required: true
        default: '50000..99999'
      sampleCode:
        description: Include Sample code?
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateTestApp:
    needs: [ ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Dump Workflow Information
        uses: mazhelez/AL-Go/Actions/DumpWorkflowInfo@split-build
        with:
          shell: pwsh

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: mazhelez/AL-Go/Actions/WorkflowInitialize@split-build
        with:
          shell: pwsh
          eventId: "DO0095"

      - name: Read settings
        uses: mazhelez/AL-Go/Actions/ReadSettings@split-build
        with:
          shell: pwsh

      - name: Read secrets
        id: ReadSecrets
        uses: mazhelez/AL-Go/Actions/ReadSecrets@split-build
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Creating a new test app
        uses: mazhelez/AL-Go/Actions/CreateApp@split-build
        with:
          shell: pwsh
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: 'Test App'
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: mazhelez/AL-Go/Actions/WorkflowPostProcess@split-build
        with:
          shell: pwsh
          eventId: "DO0095"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
